/**
 * Data model bridge — converters between the three slide models.
 *
 * The project has three models for slide data:
 *   1. SlideEdit     (Runs pipeline — server-persisted)
 *   2. SlideSpec     (Design Editor — localStorage)
 *   3. LLMSlideContent (Agent internal — generated by LLM)
 *
 * All converters produce SlideRenderSpec, the unified template input.
 */
import type { SlideRenderSpec } from "./templates/types";

// ============================================================================
// SlideEdit (Runs) → SlideRenderSpec
// ============================================================================

export interface SlideEditLike {
  slideIndex: number;
  title: string;
  bodyText: string;
  kind: string;
  templateId: string;
  imageDescription?: string;
}

export interface SlideEditConvertOpts {
  fontFamily?: string;
  footerText?: string;
  globalStyle?: Partial<SlideRenderSpec>;
}

export function slideEditToRenderSpec(
  edit: SlideEditLike,
  opts?: SlideEditConvertOpts,
): SlideRenderSpec {
  return {
    title: edit.title,
    bodyText: edit.bodyText,
    footerText: opts?.footerText ?? "",
    slideIndex: edit.slideIndex,
    fontFamily: opts?.fontFamily,
    ...opts?.globalStyle,
  };
}

// ============================================================================
// SlideSpec (Design Editor) → SlideRenderSpec
// ============================================================================

export interface SlideSpecLike {
  slideIndex: number;
  title: string;
  bodyText: string;
  footerText: string;
  templateId: string;
  heroImageDataUri?: string;
  styleOverrides?: {
    bgGradient?: string;
    textColor?: string;
    accentColor?: string;
    footerColor?: string;
    titleSizePx?: number;
    bodySizePx?: number;
    headlineSizePx?: number;
    titleWeight?: number;
    bodyWeight?: number;
    letterSpacing?: "tight" | "normal" | "wide";
    scrimOpacity?: number;
    imageBrightness?: number;
    cardRadius?: number;
  };
}

export interface SlideSpecConvertOpts {
  fontFamily?: string;
  globalStyle?: Partial<SlideRenderSpec>;
}

export function slideSpecToRenderSpec(
  spec: SlideSpecLike,
  opts?: SlideSpecConvertOpts,
): SlideRenderSpec {
  const overrides = spec.styleOverrides ?? {};
  return {
    title: spec.title,
    bodyText: spec.bodyText,
    footerText: spec.footerText,
    heroImageDataUri: spec.heroImageDataUri,
    slideIndex: spec.slideIndex,
    fontFamily: opts?.fontFamily,
    ...overrides,
    ...opts?.globalStyle,
  };
}

// ============================================================================
// LLMSlideContent (Agent) → SlideRenderSpec
// ============================================================================

export interface LLMSlideContentLike {
  slideIndex: number;
  title: string;
  bodyText: string;
  kind: string;
  imageDescription?: string;
}

export interface LLMSlideConvertOpts {
  fontFamily?: string;
  footerText?: string;
  globalStyle?: Partial<SlideRenderSpec>;
}

export function slidePlanToRenderSpec(
  plan: LLMSlideContentLike,
  opts?: LLMSlideConvertOpts,
): SlideRenderSpec {
  return {
    title: plan.title,
    bodyText: plan.bodyText,
    footerText: opts?.footerText ?? "",
    slideIndex: plan.slideIndex,
    fontFamily: opts?.fontFamily,
    ...opts?.globalStyle,
  };
}
